name: Python Build and Package
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      python_version:
        required: false
        type: string
        default: '3.11'
      requirements_file:
        required: false
        type: string
        default: 'requirements.txt'
      test_command:
        required: false
        type: string
        default: 'pytest'
      skip_tests:
        required: false
        type: boolean
        default: false
      create_release:
        required: false
        type: boolean
        default: false

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install build deps
        working-directory: ${{ inputs.working_directory }}
        run: |
          python -m pip install -U pip
          pip install -r ${{ inputs.requirements_file }}
          pip install build pytest

      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        working-directory: ${{ inputs.working_directory }}
        run: ${{ inputs.test_command }}

      - name: Build dist
        working-directory: ${{ inputs.working_directory }}
        run: python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: ${{ inputs.working_directory }}/dist/*

      - name: Attach to GitHub Release
        if: ${{ inputs.create_release }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.working_directory }}/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}