export default function TradesPage() {
  return (
    <div>
      <h1 className="mb-2 text-2xl font-semibold">Trade Recommendations</h1>
      <p className="mb-8 text-muted">
        Positions the pipeline would take based on its own analysis.
      </p>

      <div className="mb-6 rounded-md border border-orange/30 bg-orange/5 p-4 text-sm text-orange">
        <strong>Disclaimer:</strong> This is not financial advice. The
        information presented here is generated by an automated pipeline for
        educational and research purposes only. Do not make investment decisions
        based on this data.
      </div>

      <div className="rounded-md border border-border bg-surface p-8 text-center text-muted">
        Trades coming soon — will display recommendations from markettrade.
      </div>
    </div>
  );
}
