kafka:
  bootstrap: ${KAFKA_BOOTSTRAP}
  groupId: market-transformer-group
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
