kafka:
  bootstrap: "${KAFKA_BOOTSTRAP:localhost:9092}"
spring:
  rabbitmq:
    host: "${SPRING_RABBITMQ_HOST:localhost}"
    port: 5672
    username: "${SPRING_RABBITMQ_USERNAME:guest}"
    password: "${SPRING_RABBITMQ_PASSWORD:guest}"
market:
  signal:
    exchange: signal
rabbitmq:
  management:
    url: http://guest:guest@localhost:15672