kafka:
  groupId: market-transformer-group
  error-handler:
    retry-interval-ms: 1000
    max-retries: 3

price:
  sanity:
    window-size: 100
    bootstrap-threshold: 20
    deviation-threshold: 0.50

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles:
        "[quantica]": 0.5, 0.95, 0.99
