kafka:
  bootstrap: ${KAFKA_BOOTSTRAP}
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
rabbitmq:
  management:
    url: ${RABBITMQ_MANAGEMENT_URL}
