kafka:
  groupId: market-transformer-group

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles:
        "[quantica.]": 0.5, 0.95, 0.99
