kafka:
  bootstrap: "localhost:9092"
  order-topic: order
  order-topic-partitions: 4
  order-topic-replication-factor: 1

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles:
        "[quantica]": 0.5, 0.95, 0.99
