global:
  scrape_interval: 5s

scrape_configs:
  - job_name: marketlistener
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - marketlistener:8080

  - job_name: markettransformer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - markettransformer:8080

  - job_name: marketanalysis
    static_configs:
      - targets:
          - marketanalysis:8000

  - job_name: markettrade
    static_configs:
      - targets:
          - markettrade:8000

  - job_name: marketbard
    static_configs:
      - targets:
          - marketbard:8001

  - job_name: marketnotify
    static_configs:
      - targets:
          - marketnotify:8000
