global:
  scrape_interval: 5s

scrape_configs:
  - job_name: marketlistener
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - marketlistener:8080

  - job_name: markettransformer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - markettransformer:8080
