[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "marketrisk"
version = "2.1.2.dev0"
description = "Market risk service"
authors = [{name = "Nicholas Negrete", email = "negretenico0@gmail.com"}]
dependencies = [
    "python-dotenv==1.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["marketrisk"]

[tool.pytest.ini_options]
pythonpath = ["."]
