[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "markettrade"
version = "2.1.2.dev0"
description = "Market trade risk service"
authors = [{name = "Nicholas Negrete", email = "negretenico0@gmail.com"}]
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["."]
