[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "marketserver"
version = "3.6.2.dev0"
description = "Blob HTTP server for serving JSON blobs"
authors = [{name = "Nicholas Negrete", email = "negretenico0@gmail.com"}]
dependencies = [
    "Flask==3.1.3",
    "python-dotenv==1.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
