name: Listener Service CI/CD
permissions:
  contents: read
  packages: write  # Add this permission at the workflow level
on:
  push:
    paths:
      - 'marketListener/**'
      - 'shared/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'marketListener/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  java-build:
    uses: ./.github/workflows/reusable-java-build.yaml
    with:
      working_directory: ./marketListener
      java_version: '21'
      skip_tests: false
    secrets: inherit

  docker-deploy:
    needs: java-build  # Wait for java-build to complete
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      working_directory: ./marketListener
      dockerfile_path: ./marketListener/Dockerfile
      service_name: marketListener  # Correct input for docker build
      # Add other docker-specific inputs here
    secrets: inherit