name: Listener Service CI/CD
on:
  push:
    paths:
      - 'marketListener/**'
      - 'shared/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'marketListener/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Java application
        uses: ./.github/actions/java-build
        with:
          working_directory: ./marketListener
          java_version: '21'
          skip_tests: false

      - name: Build and push Docker image
        uses: ./.github/actions/docker-build
        with:
          working_directory: ./marketListener
          service_name: marketListener